name: Schematic_Loader
author: svile
description: Schematic loader plugin
main: svile\sch\SCHmain
version: 0.7
api: [3.2 4.0.0]
load: STARTUP

commands:
 sch:
  description: Schematic_Loader main command
